 	;

    
    
    ;	;9 DAN 0 kadar geriye ekranda yazan kod
;	list		p=16f877A	
;	#include	<p16f877A.inc>	
;	
;	__CONFIG H'3F31'
;G1	EQU 0x20
;G2	EQU 0x21
;G3	EQU 0x22
;SAYAC	EQU 0x23
;SAYI_L	EQU 0x24
;SAYI_H	EQU 0x25
;TEMP_L	EQU 0x26
;BINLER	EQU 0x27
;YUZLER	EQU 0x28
;ONLAR	EQU 0x29
;BIRLER	EQU 0x30
;SAYI_1	EQU 0x31
;SAYI_2	EQU 0x32
;;*******************************
;	ORG 0x000
;	NOP
;	GOTO	BAS
;;***************************
;	ORG 0x004
;	RETFIE
;;***************************
;ASCII_LOOKUP
;	ADDWF   PCL,1
;	RETLW   0x30
;	RETLW   0x31
;	RETLW   0x32
;	RETLW   0x33
;	RETLW   0x34
;	RETLW   0x35
;	RETLW   0x36
;	RETLW   0x37
;	RETLW   0x38
;	RETLW   0x39
;;;*************************************
;GECIKME
;;	MOVLW	0x01
;;	MOVWF	G1
;	MOVLW	0x50
;	MOVWF	G2
;	MOVLW	0xFF
;	MOVWF	G3
;	
;LOOP
;	DECFSZ	G3,1
;	GOTO	LOOP
;	DECFSZ	G2,1
;	GOTO	LOOP
;;	DECFSZ	G1,1
;;	GOTO	LOOP
;	RETURN
;;***************************
;USART_AYAR
;	BANKSEL	TRISC
;	MOVLW	B'10000000'
;	MOVWF	TRISC
;	
;	MOVLW	0x19
;	MOVWF	SPBRG
;	
;	MOVLW	0x26
;	MOVWF	TXSTA
;	
;	BANKSEL	RCSTA
;	MOVLW	0x90
;	MOVWF	RCSTA
;	RETURN	
;;**************************
;KESME_AYAR
;	BANKSEL	PIE1
;	BCF	PIE1,TXIE
;	
;	BANKSEL	INTCON
;	BCF	INTCON,GIE
;	RETURN
;;************************
;SERI_GONDER
;	BTFSS	PIR1,TXIF
;	GOTO	$-1
;	
;	BCF	PIR1,TXIF
;	BANKSEL	TXREG
;	MOVWF	TXREG
;	RETURN
;;*****************************	
;CEVIR
;	MOVF	SAYI_H,1
;	BTFSC	STATUS,Z
;	GOTO	ATLA
;	CALL	CEVIR_H
;ATLA
;	CALL	CEVIR_L
;	RETURN
;;****************************
;CEVIR_H
;	MOVF	SAYI_L,W
;	MOVWF	TEMP_L
;HH
;	INCF	BIRLER,1
;	MOVLW	0xFF
;	MOVWF	SAYI_L
;	CALL	CEVIR_L
;	DECFSZ	SAYI_H,1
;	GOTO	HH
;	
;	MOVF	TEMP_L,W
;	MOVWF	SAYI_L
;	RETURN
;;****************************
;CEVIR_L
;	BCF	STATUS,Z
;	MOVF	SAYI_L,1
;	BTFSC	STATUS,Z
;	RETURN
;	
;	BCF	STATUS,Z
;	DECF	SAYI_L,1
;	INCF	BIRLER,1
;	MOVLW	0x0A
;	SUBWF	BIRLER,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	
;	BCF	STATUS,Z
;	CLRF	BIRLER
;	INCF	ONLAR,1
;	MOVLW	0x0A
;	SUBWF	ONLAR,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	
;	BCF	STATUS,Z
;	CLRF	ONLAR
;	INCF	YUZLER,1
;	MOVLW	0x0A
;	SUBWF	YUZLER,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	
;	BCF	STATUS,Z
;	CLRF	YUZLER
;	INCF	BINLER,1
;	MOVLW	0x0A
;	SUBWF	BINLER,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	RETURN
;;******************************
;ASCII_AYAR
;	MOVF	BINLER,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	
;	MOVF	YUZLER,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	
;	MOVF	ONLAR,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	
;	MOVF	BIRLER,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	RETURN
;;*********************************
;ISLEM
;	MOVF	SAYI_1,W
;;	MOVWF	SAYI_1
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	DECF	SAYI_1,1
;	MOVLW	0x2F
;	SUBWF	SAYI_1,0
;	BTFSS	STATUS,Z
;	GOTO	ISLEM
;	RETURN
;;*****************************
;BAS
;	CALL	USART_AYAR
;	CALL	KESME_AYAR
;	MOVLW	0x0A
;	MOVWF	SAYI_1
;	CALL	ISLEM
;	CALL	GECIKME
;QQ
;	GOTO	QQ
;	END
    
    
    ;;	;2 BYTE	LIK 2 sayinin toplami, sonuc 2 bytle olacak sekilde
;	list		p=16f877A	
;	#include	<p16f877A.inc>	
;	
;	__CONFIG H'3F31'
;G1	EQU 0x20
;G2	EQU 0x21
;G3	EQU 0x22
;SAYAC	EQU 0x23
;SAYI_L	EQU 0x24
;SAYI_H	EQU 0x25
;TEMP_L	EQU 0x26
;BINLER	EQU 0x27
;YUZLER	EQU 0x28
;ONLAR	EQU 0x29
;BIRLER	EQU 0x30
;SAYI_1	EQU 0x31
;SAYI_2	EQU 0x32
;;*******************************
;	ORG 0x000
;	NOP
;	GOTO	BAS
;;***************************
;	ORG 0x004
;	RETFIE
;;***************************
;ASCII_LOOKUP
;	ADDWF   PCL,1
;	RETLW   0x30
;	RETLW   0x31
;	RETLW   0x32
;	RETLW   0x33
;	RETLW   0x34
;	RETLW   0x35
;	RETLW   0x36
;	RETLW   0x37
;	RETLW   0x38
;	RETLW   0x39
;;;*************************************
;GECIKME
;;	MOVLW	0x01
;;	MOVWF	G1
;	MOVLW	0x50
;	MOVWF	G2
;	MOVLW	0xFF
;	MOVWF	G3
;	
;LOOP
;	DECFSZ	G3,1
;	GOTO	LOOP
;	DECFSZ	G2,1
;	GOTO	LOOP
;;	DECFSZ	G1,1
;;	GOTO	LOOP
;	RETURN
;;***************************
;USART_AYAR
;	BANKSEL	TRISC
;	MOVLW	B'10000000'
;	MOVWF	TRISC
;	
;	MOVLW	0x19
;	MOVWF	SPBRG
;	
;	MOVLW	0x26
;	MOVWF	TXSTA
;	
;	BANKSEL	RCSTA
;	MOVLW	0x90
;	MOVWF	RCSTA
;	RETURN	
;;**************************
;KESME_AYAR
;	BANKSEL	PIE1
;	BCF	PIE1,TXIE
;	
;	BANKSEL	INTCON
;	BCF	INTCON,GIE
;	RETURN
;;************************
;SERI_GONDER
;	BTFSS	PIR1,TXIF
;	GOTO	$-1
;	
;	BCF	PIR1,TXIF
;	BANKSEL	TXREG
;	MOVWF	TXREG
;	RETURN
;;*****************************	
;CEVIR
;	MOVF	SAYI_H,1
;	BTFSC	STATUS,Z
;	GOTO	ATLA
;	CALL	CEVIR_H
;ATLA
;	CALL	CEVIR_L
;	RETURN
;;****************************
;CEVIR_H
;	MOVF	SAYI_L,W
;	MOVWF	TEMP_L
;HH
;	INCF	BIRLER,1
;	MOVLW	0xFF
;	MOVWF	SAYI_L
;	CALL	CEVIR_L
;	DECFSZ	SAYI_H,1
;	GOTO	HH
;	
;	MOVF	TEMP_L,W
;	MOVWF	SAYI_L
;	RETURN
;;****************************
;CEVIR_L
;	BCF	STATUS,Z
;	MOVF	SAYI_L,1
;	BTFSC	STATUS,Z
;	RETURN
;	
;	BCF	STATUS,Z
;	DECF	SAYI_L,1
;	INCF	BIRLER,1
;	MOVLW	0x0A
;	SUBWF	BIRLER,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	
;	BCF	STATUS,Z
;	CLRF	BIRLER
;	INCF	ONLAR,1
;	MOVLW	0x0A
;	SUBWF	ONLAR,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	
;	BCF	STATUS,Z
;	CLRF	ONLAR
;	INCF	YUZLER,1
;	MOVLW	0x0A
;	SUBWF	YUZLER,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	
;	BCF	STATUS,Z
;	CLRF	YUZLER
;	INCF	BINLER,1
;	MOVLW	0x0A
;	SUBWF	BINLER,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	RETURN
;;******************************
;ASCII_AYAR
;	MOVF	BINLER,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	
;	MOVF	YUZLER,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	
;	MOVF	ONLAR,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	
;	MOVF	BIRLER,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	RETURN
;;*********************************
;ISLEM
;
;	MOVF	SAYI_2,W
;	ADDWF	SAYI_H,1
;	
;AA
;	MOVF    SAYI_1,1
;	BTFSC   STATUS,Z
;	RETURN
;	BCF	STATUS,Z
;	DECF    SAYI_1,1
;	INCF    SAYI_L,1
;	MOVLW   0x00
;	SUBWF   SAYI_L,0
;	BTFSS   STATUS,Z
;	GOTO    AA
;	CLRF    SAYI_L
;	INCF    SAYI_H,1
;	GOTO    AA
;	
;;*****************************
;BAS
;	CALL	USART_AYAR
;	CALL	KESME_AYAR
;	MOVLW	0xFF
;	MOVWF	SAYI_1
;	MOVLW	0x03
;	MOVWF	SAYI_2
;	MOVLW	0xFF
;	MOVWF	SAYI_L
;	MOVLW	0x03
;	MOVWF	SAYI_H
;	CALL	ISLEM
;	CALL	CEVIR
;	CALL	GECIKME
;	CALL	ASCII_AYAR
;
;QQ
;	GOTO	QQ
;
;	END
    
    
    
    
    ;	;1 BYTE	LIK 2 sayinin toplami, sonuc 2 bytle olacak sekilde
;	list		p=16f877A	
;	#include	<p16f877A.inc>	
;	
;	__CONFIG H'3F31'
;G1	EQU 0x20
;G2	EQU 0x21
;G3	EQU 0x22
;SAYAC	EQU 0x23
;SAYI_L	EQU 0x24
;SAYI_H	EQU 0x25
;TEMP_L	EQU 0x26
;BINLER	EQU 0x27
;YUZLER	EQU 0x28
;ONLAR	EQU 0x29
;BIRLER	EQU 0x30
;SAYI_1	EQU 0x31
;SAYI_2	EQU 0x32
;;*******************************
;	ORG 0x000
;	NOP
;	GOTO	BAS
;;***************************
;	ORG 0x004
;	RETFIE
;;***************************
;ASCII_LOOKUP
;	ADDWF   PCL,1
;	RETLW   0x30
;	RETLW   0x31
;	RETLW   0x32
;	RETLW   0x33
;	RETLW   0x34
;	RETLW   0x35
;	RETLW   0x36
;	RETLW   0x37
;	RETLW   0x38
;	RETLW   0x39
;;;*************************************
;GECIKME
;;	MOVLW	0x01
;;	MOVWF	G1
;	MOVLW	0x50
;	MOVWF	G2
;	MOVLW	0xFF
;	MOVWF	G3
;	
;LOOP
;	DECFSZ	G3,1
;	GOTO	LOOP
;	DECFSZ	G2,1
;	GOTO	LOOP
;;	DECFSZ	G1,1
;;	GOTO	LOOP
;	RETURN
;;***************************
;USART_AYAR
;	BANKSEL	TRISC
;	MOVLW	B'10000000'
;	MOVWF	TRISC
;	
;	MOVLW	0x19
;	MOVWF	SPBRG
;	
;	MOVLW	0x26
;	MOVWF	TXSTA
;	
;	BANKSEL	RCSTA
;	MOVLW	0x90
;	MOVWF	RCSTA
;	RETURN	
;;**************************
;KESME_AYAR
;	BANKSEL	PIE1
;	BCF	PIE1,TXIE
;	
;	BANKSEL	INTCON
;	BCF	INTCON,GIE
;	RETURN
;;************************
;SERI_GONDER
;	BTFSS	PIR1,TXIF
;	GOTO	$-1
;	
;	BCF	PIR1,TXIF
;	BANKSEL	TXREG
;	MOVWF	TXREG
;	RETURN
;;*****************************	
;CEVIR
;	MOVF	SAYI_H,1
;	BTFSC	STATUS,Z
;	GOTO	ATLA
;	CALL	CEVIR_H
;ATLA
;	CALL	CEVIR_L
;	RETURN
;;****************************
;CEVIR_H
;	MOVF	SAYI_L,W
;	MOVWF	TEMP_L
;HH
;	INCF	BIRLER,1
;	MOVLW	0xFF
;	MOVWF	SAYI_L
;	CALL	CEVIR_L
;	DECFSZ	SAYI_H,1
;	GOTO	HH
;	
;	MOVF	TEMP_L,W
;	MOVWF	SAYI_L
;	RETURN
;;****************************
;CEVIR_L
;	BCF	STATUS,Z
;	MOVF	SAYI_L,1
;	BTFSC	STATUS,Z
;	RETURN
;	
;	BCF	STATUS,Z
;	DECF	SAYI_L,1
;	INCF	BIRLER,1
;	MOVLW	0x0A
;	SUBWF	BIRLER,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	
;	BCF	STATUS,Z
;	CLRF	BIRLER
;	INCF	ONLAR,1
;	MOVLW	0x0A
;	SUBWF	ONLAR,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	
;	BCF	STATUS,Z
;	CLRF	ONLAR
;	INCF	YUZLER,1
;	MOVLW	0x0A
;	SUBWF	YUZLER,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	
;	BCF	STATUS,Z
;	CLRF	YUZLER
;	INCF	BINLER,1
;	MOVLW	0x0A
;	SUBWF	BINLER,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	RETURN
;;******************************
;ASCII_AYAR
;	MOVF	BINLER,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	
;	MOVF	YUZLER,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	
;	MOVF	ONLAR,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	
;	MOVF	BIRLER,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	RETURN
;;*********************************
;ISLEM
;	CLRF	SAYI_L
;	CLRF	SAYI_H
;	MOVF	SAYI_1,W
;	MOVWF	SAYI_L
;	
;AA
;	MOVF    SAYI_2,1
;	BTFSC   STATUS,Z
;	RETURN
;	BCF	STATUS,Z
;	DECF    SAYI_2,1
;	INCF    SAYI_L,1
;	MOVLW   0x00
;	SUBWF   SAYI_L,0
;	BTFSS   STATUS,Z
;	GOTO    AA
;	CLRF    SAYI_L
;	INCF    SAYI_H,1
;	GOTO    AA
;	
;;*****************************
;BAS
;	CALL	USART_AYAR
;	CALL	KESME_AYAR
;	MOVLW	0xFF
;	MOVWF	SAYI_1
;	MOVLW	0x10
;	MOVWF	SAYI_2
;	CALL	ISLEM
;	CALL	CEVIR
;	CALL	GECIKME
;	CALL	ASCII_AYAR
;
;QQ
;	GOTO	QQ
;
;	END
    
    
    
    
    ;    ;2BYTE lik 2 sayinin toplamini dolayl? adresleme ve normal sekilde  karsiya veri gonderme
;	list		p=16f877A	
;	#include	<p16f877A.inc>	
;	
;	__CONFIG H'3F31'
;G1	EQU 0x20
;G2	EQU 0x21
;G3	EQU 0x22
;SAYAC	EQU 0x23
;SAYI_L	EQU 0x24
;SAYI_H	EQU 0x25
;TEMP_L	EQU 0x26
;BINLER	EQU 0x27
;YUZLER	EQU 0x28
;ONLAR	EQU 0x29
;BIRLER	EQU 0x30
;;*******************************
;	ORG 0x000
;	NOP
;	GOTO	BAS
;;***************************
;	ORG 0x004
;	RETFIE
;;***************************
;ASCII_LOOKUP
;	ADDWF   PCL,1
;	RETLW   0x30
;	RETLW   0x31
;	RETLW   0x32
;	RETLW   0x33
;	RETLW   0x34
;	RETLW   0x35
;	RETLW   0x36
;	RETLW   0x37
;	RETLW   0x38
;	RETLW   0x39
;;;*************************************
;GECIKME
;;	MOVLW	0x01
;;	MOVWF	G1
;	MOVLW	0x50
;	MOVWF	G2
;	MOVLW	0xFF
;	MOVWF	G3
;	
;LOOP
;	DECFSZ	G3,1
;	GOTO	LOOP
;	DECFSZ	G2,1
;	GOTO	LOOP
;;	DECFSZ	G1,1
;;	GOTO	LOOP
;	RETURN
;;***************************
;USART_AYAR
;	BANKSEL	TRISC
;	MOVLW	B'10000000'
;	MOVWF	TRISC
;	
;	MOVLW	0x19
;	MOVWF	SPBRG
;	
;	MOVLW	0x26
;	MOVWF	TXSTA
;	
;	BANKSEL	RCSTA
;	MOVLW	0x90
;	MOVWF	RCSTA
;	RETURN	
;;**************************
;KESME_AYAR
;	BANKSEL	PIE1
;	BCF	PIE1,TXIE
;	
;	BANKSEL	INTCON
;	BCF	INTCON,GIE
;	RETURN
;;************************
;SERI_GONDER
;	BTFSS	PIR1,TXIF
;	GOTO	$-1
;	
;	BCF	PIR1,TXIF
;	BANKSEL	TXREG
;	MOVWF	TXREG
;	RETURN
;;*****************************	
;CEVIR
;	MOVF	SAYI_H,1
;	BTFSC	STATUS,Z
;	GOTO	ATLA
;	CALL	CEVIR_H
;ATLA
;	CALL	CEVIR_L
;	RETURN
;;****************************
;CEVIR_H
;	MOVF	SAYI_L,W
;	MOVWF	TEMP_L
;HH
;	INCF	BIRLER,1
;	MOVLW	0xFF
;	MOVWF	SAYI_L
;	CALL	CEVIR_L
;	DECFSZ	SAYI_H,1
;	GOTO	HH
;	
;	MOVF	TEMP_L,W
;	MOVWF	SAYI_L
;	RETURN
;;****************************
;CEVIR_L
;	BCF	STATUS,Z
;	MOVF	SAYI_L,1
;	BTFSC	STATUS,Z
;	RETURN
;	
;	BCF	STATUS,Z
;	DECF	SAYI_L,1
;	INCF	BIRLER,1
;	MOVLW	0x0A
;	SUBWF	BIRLER,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	
;	BCF	STATUS,Z
;	CLRF	BIRLER
;	INCF	ONLAR,1
;	MOVLW	0x0A
;	SUBWF	ONLAR,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	
;	BCF	STATUS,Z
;	CLRF	ONLAR
;	INCF	YUZLER,1
;	MOVLW	0x0A
;	SUBWF	YUZLER,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	
;	BCF	STATUS,Z
;	CLRF	YUZLER
;	INCF	BINLER,1
;	MOVLW	0x0A
;	SUBWF	BINLER,0
;	BTFSS	STATUS,Z
;	GOTO	CEVIR_L
;	RETURN
;;******************************
;ASCII_AYAR
;	MOVF	BINLER,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	
;	MOVF	YUZLER,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	
;	MOVF	ONLAR,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	
;	MOVF	BIRLER,W
;	CALL	ASCII_LOOKUP
;	CALL	SERI_GONDER
;	CALL	GECIKME
;	RETURN
;;*********************************
;BAS
;	CALL	USART_AYAR
;	CALL	KESME_AYAR
;	MOVLW	0x27
;	MOVWF	SAYAC
;	MOVLW	0xFF
;	MOVWF	SAYI_L
;	MOVLW	0x03
;	MOVWF	SAYI_H
;	CALL	CEVIR
;	CALL	ASCII_AYAR
;	CALL	GECIKME
;;AA
;;	MOVF	SAYAC,W
;;	MOVWF	FSR
;;	MOVF	INDF,W
;;	CALL	SERI_GONDER
;;	CALL	GECIKME
;;	INCF	SAYAC,1
;;	MOVLW	0x31
;;	SUBWF	SAYAC,0
;;	BTFSS	STATUS,Z
;;	GOTO	AA
;	
;FF
;	GOTO	FF
;	END
    
	
	
	
    
        ;dolayl? adresleme ile karsiya veri gonderme
	list		p=16f877A	
	#include	<p16f877A.inc>	
	
	__CONFIG H'3F31'
G1	EQU 0x20
G2	EQU 0x21
G3	EQU 0x22
SAYAC	EQU 0x23
SAYI_L	EQU 0x24
SAYI_H	EQU 0x25
;*******************************
	ORG 0x000
	NOP
	GOTO	BAS
;***************************
	ORG 0x004
	RETFIE
;***************************
GECIKME
;	MOVLW	0x01
;	MOVWF	G1
	MOVLW	0x50
	MOVWF	G2
	MOVLW	0xFF
	MOVWF	G3
	
LOOP
	DECFSZ	G3,1
	GOTO	LOOP
	DECFSZ	G2,1
	GOTO	LOOP
;	DECFSZ	G1,1
;	GOTO	LOOP
	RETURN
;***************************
USART_AYAR
	BANKSEL	TRISC
	MOVLW	B'10000000'
	MOVWF	TRISC
	
	MOVLW	0x19
	MOVWF	SPBRG
	
	MOVLW	0x26
	MOVWF	TXSTA
	
	BANKSEL	RCSTA
	MOVLW	0x90
	MOVWF	RCSTA
	RETURN	
;**************************
KESME_AYAR
	BANKSEL	PIE1
	BCF	PIE1,TXIE
	
	BANKSEL	INTCON
	BCF	INTCON,GIE
	RETURN
;************************
SERI_GONDER
	BTFSS	PIR1,TXIF
	GOTO	$-1
	
	BCF	PIR1,TXIF
	BANKSEL	TXREG
	MOVWF	TXREG
	RETURN
;*****************************	
BAS
	CALL	USART_AYAR
	CALL	KESME_AYAR
	MOVLW	0x23
	MOVWF	SAYAC
	MOVLW	0x30
	MOVWF	SAYI_L
	MOVLW	0x31
	MOVWF	SAYI_H
	
AA
	MOVF	SAYAC,W
	MOVWF	FSR
	MOVF	INDF,W
	CALL	SERI_GONDER
	CALL	GECIKME
	INCF	SAYAC,1
	MOVLW	0x26
	SUBWF	SAYAC,0
	BTFSS	STATUS,Z
	GOTO	AA
	
	
FF
	GOTO	FF
	END